spring.application.name: ai-movie-prompt-service

client:
  openai:
    key: ${OPEN_AI_KEY}
    endpoint: ${OPEN_AI_ENDPOINT}
    deployment_name: ${AI_DEPLOYMENT_NAME}
    modellist: ${AI_DEPLOYMENT_NAME_LIST}

